<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Child;
use App\Models\Student;
use App\Models\User;
use App\Models\TrainingCenter;

class AssignStudentsToCentersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (TrainingCenter::count() == 0) {
            $this->call(TrainingCenterSeeder::class);
        }
        
        $centerIds = TrainingCenter::pluck('id')->toArray();

        // 1. Fix existing children with no training center
        $children = Child::whereNull('training_center_id')->get();
        foreach ($children as $child) {
            $child->training_center_id = fake()->randomElement($centerIds);
            $child->is_active = true;
            $child->save();
            $this->ensureStudentRecord($child);
        }

        // 2. If we have very few children, generate dummy data
        if (Child::count() < 10) {
            $this->command->info('Creating 20 new random parents and children...');
            
            // Create 20 parents
            $parents = User::factory(20)->create(['role' => 'user']);
            
            foreach ($parents as $parent) {
                // Create 1-3 children per parent
                $count = rand(1, 3);
                for ($i = 0; $i < $count; $i++) {
                    $child = Child::create([
                        'parent_id' => $parent->id,
                        'name' => fake()->firstName() . ' ' . fake()->lastName(),
                        'ic_number' => fake()->numerify('############'),
                        'date_of_birth' => fake()->date('Y-m-d', '-5 years'),
                        'belt_level' => 'white', // required default
                        'training_center_id' => fake()->randomElement($centerIds),
                        'is_active' => true,
                    ]);
                    
                    $this->ensureStudentRecord($child, $parent);
                }
            }
        } else {
            // Just ensure all existing children have student records
            foreach (Child::with('user')->get() as $child) {
                $this->ensureStudentRecord($child, $child->user);
            }
        }
        
        $this->command->info('All children assigned to training centers and have student records.');
    }

    private function ensureStudentRecord($child, $parent = null)
    {
        if (!$child->student_id) {
            $student = Student::create([
                // 'child_id' => $child->id, // Removed, column doesn't exist
                // no_siri auto-generated by model event if not supplied, but let's supply to match format
                'nama_pelajar' => $child->name,
                'nama_penjaga' => $parent ? $parent->name : 'Unknown Parent',
                'alamat' => $parent && \Illuminate\Support\Facades\Schema::hasColumn('users', 'address') && $parent->address ? $parent->address : 'Alamat Test 123',
                'no_tel' => $parent && \Illuminate\Support\Facades\Schema::hasColumn('users', 'phone_number') && $parent->phone_number ? $parent->phone_number : '0123456789',
                'kategori' => 'kanak-kanak',
                'status_bayaran' => 1,
                'tarikh_kemaskini' => now(), // Matches model
            ]);

            $child->student_id = $student->id;
            $child->save();
        }
    }
}
