<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Student;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // No Siri is auto-generated by the model event, so we don't need to specify it manually.
        // However, if we are mass seeding and the listener logic depends on the specific sequence,
        // we should ensure it works. To be safe given the seed error "no_siri doesn't have default value",
        // we will manually provide it here or ensure the Model boot works.
        // It seems the Model boot works for `create` calls one by one.

        // Explicitly ensuring no_siri is created if the boot method fails during seeding context
        // OR simply passing it to be safe.
        // Let's rely on the generateNoSiri static helper we saw in the Model.

        Student::create([
            'no_siri' => Student::generateNoSiri(),
            'nama_pelajar' => 'ALI BIN ABU',
            'nama_penjaga' => 'ABU BIN AHMAD',
            'alamat' => 'No. 14 Jalan Cendana 3, Kampung Tersusun, 13200 Kepala Batas',
            'no_tel' => '012-3456789',
            'kategori' => 'kanak-kanak',
            'status_bayaran' => 7,
            'tarikh_kemaskini' => now(),
        ]);

        Student::create([
            'no_siri' => Student::generateNoSiri(),
            'nama_pelajar' => 'SITI AMINAH BINTI HASSAN',
            'nama_penjaga' => 'HASSAN BIN IBRAHIM',
            'alamat' => 'No. 25 Taman Permai, 13200 Kepala Batas',
            'no_tel' => '013-9876543',
            'kategori' => 'kanak-kanak',
            'status_bayaran' => 12,
            'tarikh_kemaskini' => now(),
        ]);

        Student::create([
            'no_siri' => Student::generateNoSiri(),
            'nama_pelajar' => 'AHMAD FAIZ BIN RAHMAN',
            'nama_penjaga' => 'RAHMAN BIN ABDULLAH',
            'alamat' => 'No. 8 Jalan Mawar, Taman Sejahtera, 13200 Kepala Batas',
            'no_tel' => '014-2345678',
            'kategori' => 'dewasa',
            'status_bayaran' => 6,
            'tarikh_kemaskini' => now(),
        ]);

        Student::create([
            'no_siri' => Student::generateNoSiri(),
            'nama_pelajar' => 'NUR AISYAH BINTI YUSOF',
            'nama_penjaga' => 'YUSOF BIN MAHMUD',
            'alamat' => 'No. 12 Lorong Bunga Raya, 13200 Kepala Batas',
            'no_tel' => '012-8765432',
            'kategori' => 'kanak-kanak',
            'status_bayaran' => 9,
            'tarikh_kemaskini' => now(),
        ]);

        Student::create([
            'no_siri' => Student::generateNoSiri(),
            'nama_pelajar' => 'MUHAMMAD HAFIZ BIN ISMAIL',
            'nama_penjaga' => 'ISMAIL BIN OMAR',
            'alamat' => 'No. 33 Jalan Kenanga, Taman Indah, 13200 Kepala Batas',
            'no_tel' => '019-3456789',
            'kategori' => 'dewasa',
            'status_bayaran' => 10,
            'tarikh_kemaskini' => now(),
        ]);
    }
}
